name: Coleen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09139781
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: And so it began...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191410'
    - '#ffff6c'
    - '#ffba6c'
    - '#7c5448'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
