title: And so it began...
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.5167264
  lightness: 0.5
  brandColors:
    - '#FCE902'
    - '#030205'
    - '#C78803'
    - '#C9C8A3'
    - '#A24303'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Coleen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.09139781
layout_spectrum: 0.88882
